FROM ubuntu:latest

WORKDIR /root
# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    gnupg \
    git \
    wget \
    curl \
    cmake \
    ripgrep \
    gettext \
    unzip

RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | \
    gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | \
    tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install nodejs -y

# Clone the nvim.yang repository and set up Neovim
RUN git clone https://github.com/neovim/neovim.git
WORKDIR /root/neovim
RUN make CMAKE_BUILD_TYPE=Release
RUN make install
RUN git clone https://github.com/yanglited/nvim.yang ~/.config/nvim
WORKDIR /root/.config/nvim
# Build and install Neovim from source
# RUN apt-get install -y \
#     libtool-bin \
#     libtool \
#     autoconf \
#     automake \
#     pkg-config

# Clean up
# WORKDIR /root
# RUN rm -rf /root/neovim
# RUN apt-get autoremove -y && apt-get clean
# RUN rm -rf /var/lib/apt/lists/*

# Start Neovim when the container runs
# CMD ["nvim"]
